In [1]:
import numpy as np

# Gotchas

ravel() and flatten() perform the same task, but you should always use flatten() b/c it makes a copy.

b = a.ravel() # if you make changes to b, that *could* also change a. ravel is more memory efficient though, doesn't make a copy

In [24]:
a = np.random.randint(0,5,size=(4,4))
a.size

16

In [6]:
a

array([[0, 4, 1, 3],
       [0, 4, 1, 2],
       [3, 4, 2, 2],
       [0, 2, 4, 4]])

In [9]:
b = np.arange(1,20,2) #start, stop, step
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [23]:
a[-2:,]

array([[3, 4, 2, 2],
       [0, 2, 4, 4]])

In [26]:
bool_idx = (a>2)
bool_idx

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True],
       [False,  True,  True, False]])

In [27]:
c = np.array([[1,2], [3, 4], [5, 6]])

In [28]:
rows_idx, col_idx = np.where(c>=4)
rows_idx, col_idx

(array([1, 2, 2]), array([1, 0, 1]))

In [29]:
c[rows_idx, col_idx]

array([4, 5, 6])

In [30]:
# The additional syntax of a[x::y] means get every yth element starting at position x

In [33]:
q = [1,2,3,4]
rw_idx = [0,3]
np.array(q)[rw_idx]

array([1, 4])

In [34]:
# arthmetic is always done element-wise on arrays
a = np.arange(0,5)
b = np.arange(5,10)

In [39]:
from __future__ import division
a / b

array([0.        , 0.16666667, 0.28571429, 0.375     , 0.44444444])

In [40]:
a + b

array([ 5,  7,  9, 11, 13])

In [41]:
a = np.random.randint(0,10,size=(2,2))
b = np.random.randint(0,10,size=(2,2))

In [42]:
# elementwise multiplication
a*b

array([[ 6,  0],
       [10, 45]])

In [43]:
# matrix multiplication
np.dot(a,b)

array([[ 6, 14],
       [31, 59]])

In [45]:
a

array([[2, 0],
       [2, 5]])

# Understanding axis arguments for arthmetic and stats

The axis refers to the dimension that will be **COLLAPSED**

axis = 0 is rows (2D array)
axis = 1 is columns

So array.sum(axis = 0) means sum **ALONG** the rows, which will take the sum of each column

So array.sum(axis = 1) means sum **ALONG** the columns, which will take the sum of each each

In [46]:
a.mean(axis=0)

array([2. , 2.5])

In [47]:
a.mean(axis=1)

array([1. , 3.5])

### Reshape

In [48]:
a

array([[2, 0],
       [2, 5]])

In [51]:
c = a.reshape(1,a.size)
c

array([[2, 0, 2, 5]])

In [52]:
# flatten a 3d TS array into something for an RF or LR
bob = np.random.uniform(0,100,size=(20,10,5))
print(bob.shape)
jo = bob.reshape(bob.shape[0],bob.shape[1] * bob.shape[2])
jo.shape

(20, 10, 5)


(20, 50)

In [54]:
# and convert the 2D back to the 3D
bob2 = jo.reshape(jo.shape[0],10,5)

### Concat

axis = 0 is stack rows ontop of each other
axis = 1, column join

vstack: vertical stack, same as concatenate axis=0
hstack: horizontal stack, stack concatenate axis=1


In [58]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6],[7,8]])

c = np.concatenate([a,b],axis=0)
d = np.vstack([a,b])
print(c.shape,d.shape)

((4, 2), (4, 2))
